language: php
# nodejs版本
node_js:
    - '8'

# Travis-CI Caching
cache:
  directories:
    - vendor/vendor/

# S: Build Lifecycle
install:
  - cd ./vendor
  - composer install

# 构建
script:
  # - npm run build
  # - cd ./dist
  # - git init
  # - git add -A
  # - git commit -m 'deploy'
  # - git push -f https://${GITHUB_USERNAME}:${GITHUB_PASSWORD}@github.com/ijry/initadmin.git master:gh-pages

# 指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master
